name: Telmate/proxmox
resources:
    cloud_init_disk Resource - terraform-provider-proxmox:
        subCategory: ""
        description: This resource creates and manages a Proxmox Cloud Init disk.
        name: cloud_init_disk Resource - terraform-provider-proxmox
        title: cloud_init_disk Resource - terraform-provider-proxmox
        argumentDocs:
            id: '- The volume identification of the ISO.'
            sha256: '- The computed sha256 checksum'
            size: '- The volume size'
        importStatements: []
    lxc Resource - terraform-provider-proxmox:
        subCategory: ""
        description: This resource creates and manages an LXC container on Proxmox.
        name: lxc Resource - terraform-provider-proxmox
        title: lxc Resource - terraform-provider-proxmox
        argumentDocs:
            agent = 0: ) unless the installed OS contains the Agent in OS install configurations
            boot: ': a valid boot order must be specified with Network type included (eg order=scsi0;net0)'
            disks.ide: ': Disks.Ide Block.'
            disks.ide.cdrom: ': Disks.x.Cdrom Block.'
            disks.ide.cloudinit: ': Disks.x.Cloudinit Block.'
            disks.ide.disk: ': Disks.x.Disk Block.'
            disks.ide.passthrough: ': Disks.x.Passthrough Block.'
            disks.sata: ': Disks.Sata Block.'
            disks.sata.cdrom: ': Disks.x.Cdrom Block.'
            disks.sata.cloudinit: ': Disks.x.Cloudinit Block.'
            disks.sata.disk: ': Disks.x.Disk Block.'
            disks.sata.passthrough: ': Disks.x.Passthrough Block.'
            disks.scsi: ': Disks.Scsi Block.'
            disks.scsi.cdrom: ': Disks.x.Cdrom Block.'
            disks.scsi.cloudinit: ': Disks.x.Cloudinit Block.'
            disks.scsi.disk: ': Disks.x.Disk Block.'
            disks.scsi.passthrough: ': Disks.x.Passthrough Block.'
            disks.virtio: ': Disks.Virtio Block.'
            disks.virtio.cdrom: ': Disks.x.Cdrom Block.'
            disks.virtio.disk: ': Disks.x.Disk Block.'
            disks.virtio.passthrough: ': Disks.x.Passthrough Block.'
            usbs.device: ': USBs.x.Device Block.'
            usbs.mapping: ': USBs.x.Mapping Block.'
            usbs.port: ': USBs.x.Port Block.'
            usbs.spice: ': USBs.x.Spice Block.'
        importStatements: []
