/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DiskObservation struct {
	ACL *bool `json:"acl,omitempty" tf:"acl,omitempty"`

	Backup *bool `json:"backup,omitempty" tf:"backup,omitempty"`

	Container *string `json:"container,omitempty" tf:"container,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Mountoptions []MountoptionsObservation `json:"mountoptions,omitempty" tf:"mountoptions,omitempty"`

	Mp *string `json:"mp,omitempty" tf:"mp,omitempty"`

	Quota *bool `json:"quota,omitempty" tf:"quota,omitempty"`

	Replicate *bool `json:"replicate,omitempty" tf:"replicate,omitempty"`

	Shared *bool `json:"shared,omitempty" tf:"shared,omitempty"`

	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	Slot *float64 `json:"slot,omitempty" tf:"slot,omitempty"`

	Storage *string `json:"storage,omitempty" tf:"storage,omitempty"`

	Volume *string `json:"volume,omitempty" tf:"volume,omitempty"`
}

type DiskParameters struct {

	// +kubebuilder:validation:Optional
	ACL *bool `json:"acl,omitempty" tf:"acl,omitempty"`

	// +kubebuilder:validation:Optional
	Backup *bool `json:"backup,omitempty" tf:"backup,omitempty"`

	// +kubebuilder:validation:Optional
	Container *string `json:"container,omitempty" tf:"container,omitempty"`

	// +kubebuilder:validation:Optional
	Mountoptions []MountoptionsParameters `json:"mountoptions,omitempty" tf:"mountoptions,omitempty"`

	// +kubebuilder:validation:Optional
	Mp *string `json:"mp,omitempty" tf:"mp,omitempty"`

	// +kubebuilder:validation:Optional
	Quota *bool `json:"quota,omitempty" tf:"quota,omitempty"`

	// +kubebuilder:validation:Optional
	Replicate *bool `json:"replicate,omitempty" tf:"replicate,omitempty"`

	// +kubebuilder:validation:Optional
	Shared *bool `json:"shared,omitempty" tf:"shared,omitempty"`

	// +kubebuilder:validation:Optional
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// +kubebuilder:validation:Optional
	Slot *float64 `json:"slot,omitempty" tf:"slot,omitempty"`

	// +kubebuilder:validation:Optional
	Storage *string `json:"storage,omitempty" tf:"storage,omitempty"`

	// +kubebuilder:validation:Optional
	Volume *string `json:"volume,omitempty" tf:"volume,omitempty"`
}

type MountoptionsObservation struct {
	Noatime *bool `json:"noatime,omitempty" tf:"noatime,omitempty"`

	Nodev *bool `json:"nodev,omitempty" tf:"nodev,omitempty"`

	Noexec *string `json:"noexec,omitempty" tf:"noexec,omitempty"`

	Nosuid *bool `json:"nosuid,omitempty" tf:"nosuid,omitempty"`
}

type MountoptionsParameters struct {

	// +kubebuilder:validation:Optional
	Noatime *bool `json:"noatime,omitempty" tf:"noatime,omitempty"`

	// +kubebuilder:validation:Optional
	Nodev *bool `json:"nodev,omitempty" tf:"nodev,omitempty"`

	// +kubebuilder:validation:Optional
	Noexec *string `json:"noexec,omitempty" tf:"noexec,omitempty"`

	// +kubebuilder:validation:Optional
	Nosuid *bool `json:"nosuid,omitempty" tf:"nosuid,omitempty"`
}

// DiskSpec defines the desired state of Disk
type DiskSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DiskParameters `json:"forProvider"`
}

// DiskStatus defines the observed state of Disk.
type DiskStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DiskObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Disk is the Schema for the Disks API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,proxmoxve}
type Disk struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.container)",message="container is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.mp)",message="mp is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.size)",message="size is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.slot)",message="slot is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.storage)",message="storage is a required parameter"
	Spec   DiskSpec   `json:"spec"`
	Status DiskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DiskList contains a list of Disks
type DiskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Disk `json:"items"`
}

// Repository type metadata.
var (
	Disk_Kind             = "Disk"
	Disk_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Disk_Kind}.String()
	Disk_KindAPIVersion   = Disk_Kind + "." + CRDGroupVersion.String()
	Disk_GroupVersionKind = CRDGroupVersion.WithKind(Disk_Kind)
)

func init() {
	SchemeBuilder.Register(&Disk{}, &DiskList{})
}
